# Generated by Django 5.2.4 on 2025-08-12 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="crew",
            name="position",
            field=models.CharField(
                choices=[
                    ("pilot", "Pilot"),
                    ("attendant", "Flight Attendant"),
                    ("engineer", "Engineer"),
                ],
                default="attendant",
                max_length=20,
            ),
        ),
    ]
